import { useState } from "react";
import { ChevronDown } from "lucide-react";
import Section from "./Section";

/**
 * Every line here comes from the Python engine response. The frontend does
 * not compute or invent reasoning.
 */
export default function ReasoningPanel({ explanations, reasoning, siteAdaptation }) {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <Section title="Why this design?" note="Generated by the engine" ticked>
      <div className="divide-y divide-rule border-y border-rule">
        {explanations.map((item, index) => {
          const open = openIndex === index;
          return (
            <div key={item.parameter}>
              <h3>
                <button
                  type="button"
                  className="flex w-full items-center justify-between gap-4 py-4 text-left"
                  aria-expanded={open}
                  onClick={() => setOpenIndex(open ? -1 : index)}
                >
                  <span className="font-medium text-paper">{item.question}</span>
                  <ChevronDown
                    className={`h-4 w-4 shrink-0 text-paper-faint transition-transform ${
                      open ? "rotate-180" : ""
                    }`}
                    aria-hidden="true"
                  />
                </button>
              </h3>
              {open && (
                <div className="grid gap-6 pb-6 sm:grid-cols-2">
                  <div>
                    <p className="annot mb-2">Inputs</p>
                    <ul className="space-y-1">
                      {item.drivers.map((driver) => (
                        <li key={driver} className="readout text-sm text-paper-muted">
                          {driver}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <p className="annot mb-2">Therefore</p>
                    <ul className="space-y-1">
                      {item.implications.map((line) => (
                        <li key={line} className="flex gap-2 text-sm text-paper-muted">
                          <span aria-hidden="true" className="text-thermal-warm">
                            &rarr;
                          </span>
                          <span>{line}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      <div className="mt-6">
        <p className="annot mb-3">Engine notes</p>
        <ul className="max-w-reading space-y-2">
          {reasoning.map((line) => (
            <li key={line} className="text-sm leading-relaxed text-paper-muted">
              {line}
            </li>
          ))}
        </ul>
      </div>

      {siteAdaptation && siteAdaptation.length > 0 && (
        <div className="mt-6 border-t border-rule pt-6">
          <p className="annot mb-3">If this exact design cannot be built here</p>
          <p className="mb-3 max-w-reading text-sm text-paper-muted">
            Two identically classified climates can still sit on very
            different plots. These recommendations assume no site
            constraint; if the plot forces a compromise, prioritise in this
            order:
          </p>
          <ul className="max-w-reading space-y-2">
            {siteAdaptation.map((line) => (
              <li key={line} className="flex gap-2 text-sm text-paper-muted">
                <span aria-hidden="true" className="text-thermal-warm">
                  &rarr;
                </span>
                <span>{line}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </Section>
  );
}
